---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Confirm Kafka folder has been created
      stat:
        path: /opt/kafka/
      register: result_details

    - name: Assert Kafka exists
      assert:
        that:
          - "result_details.stat.exists"
